spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQLPORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  server:
    port: ${PORT:8080}


